### ISSUE TITLE
web gui small issue

### ISSUE THREAD

**Issue by vosonwang** [syncthing/docs#410]
it works. everything is ok.
but the web gui had a small issue.
console:

TypeError: Cannot read property '$name' of undefined
    at ChildScope.$scope.loadFormIntoScope (http://localhost:8384/syncthing/core/syncthingController.js:1545:50)
    at $parseFunctionCall (http://localhost:8384/vendor/angular/angular.js:12493:18)
    at ChildScope.$eval (http://localhost:8384/vendor/angular/angular.js:14589:28)
    at pre (http://localhost:8384/vendor/angular/angular.js:22621:15)
    at invokeLinkFn (http://localhost:8384/vendor/angular/angular.js:8300:9)
    at nodeLinkFn (http://localhost:8384/vendor/angular/angular.js:7789:11)
    at compositeLinkFn (http://localhost:8384/vendor/angular/angular.js:7159:13)
    at nodeLinkFn (http://localhost:8384/vendor/angular/angular.js:7805:24)
    at compositeLinkFn (http://localhost:8384/vendor/angular/angular.js:7159:13)
    at compositeLinkFn (http://localhost:8384/vendor/angular/angular.js:7162:13) <ul class="nav nav-tabs" ng-init="loadFormIntoScope(folderEditor)">

**Comment by calmh** [comment]
This is the documentation repo, you want https://github.com/syncthing/syncthing/issues/new, thanks.
